# controller_frequency: 20.0
# recovery_behavior_enabled: false
# clearing_rotation_allowed: false
#
# TrajectoryPlannerROS:
#    max_vel_x: 0.8
#    min_vel_x: 0.2
#    max_rotational_vel: 4
#    min_in_place_vel_theta: 0.5
#    escape_vel: -0.1
#    acc_lim_x: 1
#    acc_lim_y: 1
#    acc_lim_th: 8
#
#    holonomic_robot: false
#    yaw_goal_tolerance: 0.1 # about 6 degrees
#    xy_goal_tolerance: 0.05  # 5 cm
#    latch_xy_goal_tolerance: false
#    pdist_scale: 0.8
#    gdist_scale: 0.2
#    occdist_scale: 0.0
#    meter_scoring: true
#
#    heading_lookahead: 0.325
#    heading_scoring: true
#    heading_scoring_timestep: 0.8
#    oscillation_reset_dist: 0.05
#    publish_cost_grid_pc: false
#
#    sim_time: 1.0
#    sim_granularity: 0.025
#    angular_sim_granularity: 0.025
#    vx_samples: 15
#    vtheta_samples: 20
#    dwa: true

# no obstacles

# controller_frequency: 20.0
# recovery_behavior_enabled: false
# clearing_rotation_allowed: false
#
# TrajectoryPlannerROS:
#    max_vel_x: 0.8
#    min_vel_x: 0.2
#    max_rotational_vel: 1.0
#    min_in_place_vel_theta: 0.5
#    escape_vel: -0.1
#    acc_lim_x: 2.5
#    acc_lim_y: 2.5
#    acc_lim_th: 3.2
#
#    holonomic_robot: false
#    yaw_goal_tolerance: 0.1 # about 6 degrees
#    xy_goal_tolerance: 0.1  # 10 cm
#    latch_xy_goal_tolerance: false
#    pdist_scale: 0.8
#    gdist_scale: 0.6
#    meter_scoring: true
#
#    heading_lookahead: 0.325
#    heading_scoring: false
#    heading_scoring_timestep: 0.8
#    occdist_scale: 0.1
#    oscillation_reset_dist: 0.05
#    publish_cost_grid_pc: true
#    prune_plan: true
#
#    sim_time: 2
#    sim_granularity: 0.025
#    angular_sim_granularity: 0.025
#    vx_samples: 8
#    vtheta_samples: 20
#    dwa: true
#    simple_attractor: false


controller_frequency: 20.0
recovery_behavior_enabled: false
clearing_rotation_allowed: false

TrajectoryPlannerROS:
    max_vel_x: 0.8
    min_vel_x: 0.1
    max_rotational_vel: 4
    min_in_place_vel_theta: 0.5
    escape_vel: -0.1
    acc_lim_x: 0.8
    acc_lim_y: 0.8
    acc_lim_th: 8

    holonomic_robot: false
    yaw_goal_tolerance: 0.1 # about 6 degrees
    xy_goal_tolerance: 0.1  # 10 cm
    latch_xy_goal_tolerance: false
    pdist_scale: 0.8
    gdist_scale: 0.6
    meter_scoring: true

    heading_lookahead: 0.325
    heading_scoring: false
    heading_scoring_timestep: 0.8
    occdist_scale: 0.1
    oscillation_reset_dist: 0.05
    publish_cost_grid_pc: true
    prune_plan: true

    sim_time: 2.7
    sim_granularity: 0.025
    angular_sim_granularity: 0.025
    vx_samples: 15
    vtheta_samples: 40
    dwa: false

# DWAPlannerROS:
#   acc_lim_x: 1.2
#   acc_lim_y: 1.2
#   acc_lim_th: 8
#   max_trans_vel: 0.8
#   min_trans_vel: 0.1
#   max_vel_x: 0.8
#   min_vel_x: 0.1
#   max_vel_y: 0
#   min_vel_y: 0
#   max_rot_vel: 4
#   min_rot_vel: 0.5
#
#   yaw_goal_tolerance: 0.1
#   xy_goal_tolerance: 0.1
#   latch_xy_goal_tolerance: false
#   sim_time: 1.7
#   sim_granularity: 0.025
#   vx_samples: 20
#   vy_samples: 20
#   vtheta_samples: 40
#   controller_frequency: 20
#   penalize_negative_x: true
#
#   path_distance_bias: 32.0
#   goal_distance_bias: 5.0
#   occdist_scale: 0.01
#   forward_point_distance: 0.325
#   stop_time_buffer: 0.2
#   scaling_speed: 0.25
#   max_scaling_factor: 0.2
#   oscillation_reset_dist: 0.1
#   prune_plan: true
